#!/usr/bin/env -S unshare -rm --map-auto sh

if [ "$#" -ne "1" ]
then
	echo "USAGE: $0 <mountpoint>"
	exit 1
fi

dir="$1"
[ -e "$dir" ] || mkdir "$dir"
if [ -n "`ls "$dir"`" ]
then
	# Workaround so mount -M will not be a no-op.
	mount -B "$dir" "$dir"

	nonempty="true"
else
	mount -t tmpfs none "$dir"
	nonempty="false"
fi
cd "$dir"

ln -sf lib/x86_64-linux-gnu lib64
ln -sf usr/bin .
mkdir -p dev
mkdir -p etc
mkdir -p lib
mkdir -p usr
mount -R /dev dev
mount -Bo ro /etc etc
mount -Bo ro /lib lib
mount -Bo ro,nosuid /usr usr

mkdir -p proc
mkdir -p home
mount -t tmpfs none home
cp -r etc/skel home/nobody

if "$nonempty"
then
	chown nobody: .
else
	mount -o remount,ro none .
fi

# Allow unshare within chroot.
mount -M . / 2>/dev/null

exec env -i HOME=/home/nobody PATH="$PATH" SHELL="$SHELL" TERM="$TERM" chroot . unshare -Upf --mount-proc
