#!/usr/bin/env -S unshare -rm --map-auto sh

if [ "$#" -eq "0" ]
then
	echo "USAGE: $0 <mountpoint> [cmdline]..."
	exit 1
fi

dir="$1"
shift
[ -e "$dir" ] || mkdir "$dir"
if [ -n "`ls "$dir"`" ]
then
	# Workaround so mount -M will not be a no-op.
	mount -B "$dir" "$dir"

	[ -e "$dir/home" ] || chown -R nobody: "$dir"
	nonempty="true"
else
	mount -t tmpfs none "$dir"
	nonempty="false"
fi
cd "$dir"

ln -sf lib/x86_64-linux-gnu lib64
if [ -d bin ]
then
	ln -sf ../usr/bin/sh bin
	ln -sf "../usr/bin/`basename "$SHELL"`" bin
else
	ln -sf usr/bin .
fi

mkdir -p dev
mkdir -p etc
mkdir -p lib
mkdir -p proc
mkdir -p usr
mount -R /dev dev
mount -Bo ro /etc etc
mount -Bo ro /lib lib
mount -R /proc proc
mount -Bo ro,nosuid /usr usr

mkdir -p home/nobody
mkdir -p tmp
mount -t tmpfs none home/nobody
mount -t tmpfs none tmp
cp -r etc/skel/. home/nobody

if "$nonempty"
then
	chown nobody: home
else
	mount -o remount,ro none .
fi

# Allow unshare within unshare -R.
mount -M . / 2>/dev/null

exec env -i HOME=/home/nobody PATH="$PATH" SHELL="$SHELL" TERM="$TERM" unshare -R. unshare -Upf --mount-proc "$@"
