#!/usr/bin/env -S unshare -r --map-auto sh

# Copyright (C) 2022, Sol Boucher
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# Lesser General Public License as published by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>. 

if [ "$#" -ne "1" ]
then
	echo "USAGE: $0 <former mountpoint>"
	exit 1
fi

exec chown -R root: "$1"
